// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lufxrpmnewezmbtbmjxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1ZnhycG1uZXdlem1idGJtanhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzY4MTcsImV4cCI6MjA2OTY1MjgxN30.Yek48CZaEmsBum8k_tc1LBluHaT3AaN5H99-_SBeGUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});